title: "Rosedale Community Garden"

about: |
  Rosedale Community Garden - A Denver Urban Gardens member for over 50 years!
  <br />
  <br />
  Come visit us most Saturday Mornings for more information
markdown: kramdown
url: ""
baseurl: ""

plugins: 
  - jekyll-paginate
  - jemoji
  
paginate_path: "/page:num/"

paginate: 5

main_toc:
  - title: Home
    url: ""
  - title: About
    url: "about"
  - title: Author
    url: "author"
  - title: Garden Teams
    children:
      - title: Bees
        url: "teams_bees"
      - title: Bokashi
        url: "teams_bokashi"
      - title: "Community Flower Stand"
        url: "teams_flower_stand"
      - title: Garlic
        url: "teams_garlic"
      - title: Orchard
        url: "teams_orchard"

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
